server:
  port: 8090
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 5
    maxActive: 50
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    password: Bhcuisine88872567.
    poolPreparedStatements: false
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.97.155.171:3306/cuisine?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=FALSE
    username: bhcuisine
    validationQuery: SELECT 1 FROM DUAL


